// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQbwSPA2vQ_VfEH1sD032JSmvtkfyuN9Q',
    appId: '1:377928535925:web:c059366723158611038d3c',
    messagingSenderId: '377928535925',
    projectId: 'fir-flutter-codelab-ef081',
    authDomain: 'fir-flutter-codelab-ef081.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-ef081.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGb3PwB2cMA-AmElOtD1vz2lXAl7iCqMg',
    appId: '1:377928535925:android:1c943d98f310606d038d3c',
    messagingSenderId: '377928535925',
    projectId: 'fir-flutter-codelab-ef081',
    storageBucket: 'fir-flutter-codelab-ef081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBngc_ReyAToiCe69LQCd3jfVvfP4l1pI',
    appId: '1:377928535925:ios:061b92781827fc18038d3c',
    messagingSenderId: '377928535925',
    projectId: 'fir-flutter-codelab-ef081',
    storageBucket: 'fir-flutter-codelab-ef081.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBngc_ReyAToiCe69LQCd3jfVvfP4l1pI',
    appId: '1:377928535925:ios:061b92781827fc18038d3c',
    messagingSenderId: '377928535925',
    projectId: 'fir-flutter-codelab-ef081',
    storageBucket: 'fir-flutter-codelab-ef081.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
